drak_anti_spam:
    resource: "@DrakAntiSpamBundle/Resources/config/routing.yml"
    prefix:   /

drak_blog:
    resource: "@DrakBlogBundle/Resources/config/routing.yml"
    prefix:   /blog

# app:
#     resource: "@AppBundle/Controller/"
#     type:     annotation
