security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Drak\UserBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:            [ROLE_AUTEUR, ROLE_MODERATEUR]
        ROLE_SUPER_ADMIN:      [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    providers:
        # in_memory:
        #     memory:
        #         users:
        #             user:      { password: userpass, roles: [ 'ROLE_USER'] }
        #             admin:     { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
            main:
                # entity: { class: Drak\UserBundle\Entity\User, property: username }
                id: fos_user.user_provider.username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            pattern:          ^/
            anonymous:        true
            provider:         main
            form_login:
                login_path:   fos_user_security_login
                check_path:   fos_user_security_check
            logout:
                path:         fos_user_security_logout
                target:       /blog
            remember_me:
                key:          %secret% # %secret% est un paramètre de parameters.yml
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

