security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Drak\UserBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:            [ROLE_AUTEUR, ROLE_MODERATEUR]
        ROLE_SUPER_ADMIN:      [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    providers:
        # in_memory:
        #     memory:
        #         users:
        #             user:      { password: userpass, roles: [ 'ROLE_USER'] }
        #             admin:     { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
            main:
                entity: { class: Drak\UserBundle\Entity\User, property: username }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            pattern:      ^/
            anonymous:    true
            provider:     main
            form_login:
                login_path:   login
                check_path:   login_check
            logout:
                path:     logout
                target:   /blog
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

