services:
#    drak_blog.example:
#        class: Drak\BlogBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    drak_blog.doctrine.notification:
        class: Drak\BlogBundle\DoctrineListener\ApplicationNotification
        arguments: [@mailer]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
